### ISSUE TITLE
ab包压缩问题

### ISSUE THREAD

**Issue by RuiZhuo** [AXiX-official/Unity_CRC32_Bypass#1]
大神你好。对于压缩的ab包有解决办法吗

**Comment by AXiX-official** [comment]
可以考虑先用UABEA或者UnityPy导出解压后的ab包，修正crc后再用uabea或者unitypy压缩。主要是重新压缩写起来比较麻烦，以后可能会写

**Comment by RuiZhuo** [comment]
大神，我已经用UABE解压了。然后报这个错，是什么问题呀

C:\Users\dana>C:\Users\dana\Desktop\net8.0\Unity_CRC32_Bypass.exe C:\Users\dana\Desktop\CAB-953df5489ce7c6154beec70bcdf6ae13 C:\Users\dana\Desktop\CAB-953df5489ce7c6154beec70bcdf6ae13-2 ./Desktop
signature does not match any of the supported string signatures, attempting to check bytes signatures
Parsed signature is 0000
Parsed signature does not match with expected signature 1F8B
Parsed signature is 000000000000
Parsed signature does not match with expected signature 62726F746C69
Attempting to check if the file is serialized file...
Valid serialized file !!
Unhandled exception. System.Exception: Unsupported signature, only UnityFS is supported.
   at Unity_CRC32_Bypass.BundleFile.ReadBundleHeader(FileReader reader) in F:\Rider\Unity_CRC32_Bypass\Unity_CRC32_Bypass\BundleFile.cs:line 194
   at Unity_CRC32_Bypass.BundleFile..ctor(String path) in F:\Rider\Unity_CRC32_Bypass\Unity_CRC32_Bypass\BundleFile.cs:line 150
   at Unity_CRC32_Bypass.Program.Main(String[] args) in F:\Rider\Unity_CRC32_Bypass\Unity_CRC32_Bypass\Program.cs:line 13

**Comment by AXiX-official** [comment]
文件类型不对

**Comment by AXiX-official** [comment]
如果你仍然需要直接处理压缩的bundlefile，现在添加了支持

**Comment by RuiZhuo** [comment]
666
